#ifndef __REX_OTA_IMAGE_TYPE_DEF__
#define	__REX_OTA_IMAGE_TYPE_DEF__


typedef enum
{
	//0x00~0x10 for simon device
	REX_OTA_IMAGETYPE_STANDARD_CIE					 = 0x0012,
	REX_OTA_IMAGETYPE_MOTION_SENSOR 				 = 0x0013,
	REX_OTA_IMAGETYPE_CONTACT_SENSOR 			 	 = 0x0014,
	REX_OTA_IMAGETYPE_FIRE_SENSOR 					 = 0x0015,
	REX_OTA_IMAGETYPE_WATER_SENSOR 					 = 0x0016,
	REX_OTA_IMAGETYPE_CO_SENSOR 					 = 0x0017,
	REX_OTA_IMAGETYPE_IAS_PED						 = 0x0018,
	REX_OTA_IMAGETYPE_VIB_MOVE_SENSOR				 = 0x0019,
	REX_OTA_IMAGETYPE_REMOTE_CONTROL				 = 0x001A,
	REX_OTA_IMAGETYPE_KEY_FOB						 = 0x001B,
	REX_OTA_IMAGETYPE_KEY_PAD						 = 0x001C,
	REX_OTA_IMAGETYPE_SIREN							 = 0x001D,
	REX_OTA_IMAGETYPE_GAS_BREAK_SENSOR		 		 = 0x001E,
	REX_OTA_IMAGETYPE_SERURITY_REPEATER		 		 = 0x001F,

	REX_OTA_IMAGETYPE_COORDINATOR		 		 	 = 0x1163,
	REX_OTA_IMAGETYPE_RADIO_FREQUENCY_TEST			 = 0x1164,

	//REX_OTA_IMAGETYPE_ON_OFF_SWITCH					= 0x8000,
	REX_OTA_IMAGETYPE_LEVEL_SWITCH					 = 0x8001,
	REX_OTA_IMAGETYPE_ON_OFF_OUTPUT					 = 0x8002,
	REX_OTA_IMAGETYPE_LEVEL_OUTPUT					 = 0x8003,
	//REX_OTA_IMAGETYPE_SCENE_SELECTOR					= 0x8004,    may have multiple key
	REX_OTA_IMAGETYPE_RANGE_EXTENDER				 = 0x8008,
	REX_OTA_IMAGETYPE_MAINS_POWER_OUTLET			 = 0x8009,
	REX_OTA_IMAGETYPE_DOOR_LOCK						 = 0x800A,
	REX_OTA_IMAGETYPE_SIMPLE_SENSOR					 = 0x800C,
	REX_OTA_IMAGETYPE_CONSUMPTION_AWARE				 = 0x800D,
	REX_OTA_IMAGETYPE_PASSTHROUGH_V2				 = 0x8010,
	REX_OTA_IMAGETYPE_SLEEPY_PASSTHROUGH_V2			 = 0x8011,

	REX_OTA_IMAGETYPE_SMART_PLUG					 = 0x8051,
	REX_OTA_IMAGETYPE_METER_INTERFACE				 = 0x8053,

	//REX_OTA_IMAGETYPE_ON_OFF_LIGHT					 = 0x8100, may have multiple ep
	REX_OTA_IMAGETYPE_DIMMABLE_LIGHT				 = 0x8101,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_CW			 = 0x8102,
	//REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH				 = 0x8103, may have multiple ep
	REX_OTA_IMAGETYPE_DIMMER_SWITCH					 = 0x8104,
	REX_OTA_IMAGETYPE_COLOR_DIMMAER_SWITCH			 = 0x8105,
	REX_OTA_IMAGETYPE_LIGHT_SENSOR					 = 0x8106,
	REX_OTA_IMAGETYPE_OCCUPANCY_SENSOR				 = 0x8107,

	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT		 	= 0x8109,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_CCT		 	= 0x8110,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_RGB		 	= 0x8111,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_RGBW			= 0x8112,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_RGBCW		= 0x8113,
	REX_OTA_IMAGETYPE_COLOR_DIMMABLE_LIGHT_RGBCCT       = 0x8114,


	REX_OTA_IMAGETYPE_SHADE							 = 0x8201,
	REX_OTA_IMAGETYPE_WINDOW_COVERING_DEVICE		 = 0x8202, // 0x82X2 X 0 ~ 5 : 1 - 6 PIN 
	REX_OTA_IMAGETYPE_WINDOW_COVERING_CONTROLLER	 = 0x8203, // 0x82X3 X 0 ~ 5 : 1 - 6 PIN

	REX_OTA_IMAGETYPE_HEATING_COOLING_UNIT			 = 0x8300,
	REX_OTA_IMAGETYPE_THERMOSTAT				     = 0x8301,
	REX_OTA_IMAGETYPE_TEMPERATURE_SENSOR			 = 0x8302,
	REX_OTA_IMAGETYPE_FAN_CONTROL					 = 0x8303,
	REX_OTA_IMAGETYPE_CLOTHERS_DRYER				 = 0x8310,

	REX_OTA_IMAGETYPE_ON_OFF_SWITCH_KEY_1			 = 0x8510,
	//1-9 0x8510 ~ 0x8518
	REX_OTA_IMAGETYPE_ON_OFF_SWITCH_KEY_9			 = 0x8518,

	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_1			 = 0x8520,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_2			 = 0x8521,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_3			 = 0x8522,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_4			 = 0x8523,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_5			 = 0x8524,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_6			 = 0x8525,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_7			 = 0x8526,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_8			 = 0x8527,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_9			 = 0x8528,

	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_1			 = 0x8530, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2		 	 = 0x8531,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3			 = 0x8532,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4			 = 0x8533,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_5			 = 0x8534,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_6			 = 0x8535,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_7			 = 0x8536,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_8			 = 0x8537,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_9			 = 0x8538, 

	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_1		 = 0x8540, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_2		 = 0x8541, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_3		 = 0x8542, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_4		 = 0x8543, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_5		 = 0x8544, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_6		 = 0x8545, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_7		 = 0x8546,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_8		 = 0x8547, 
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_SWITCH_KEY_9		 = 0x8548, 

	//The folloing imagetypes are customized for laffey anxinjia's Telink project
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_1_LFB		 = 0x8549,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_LFB		 = 0x8550,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3_LFB		 = 0x8551,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4_LFB		 = 0x8552,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_1_LFB		 = 0x8553,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_2_LFB		 = 0x8554,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_3_LFB		 = 0x8555,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_4_LFB		 = 0x8556,
	REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_6_LFB		 = 0x8557,
	REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_1_LFB		 		 = 0x8558,
	REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_2_LFB		 		 = 0x8559,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_SCENE_KEY_1_LFB		 = 0x8560,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_SCENE_KEY_2_LFB		 = 0x8561,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4_SCENE_KEY_2_LFB		 = 0x8562,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_1_SCENE_KEY_3_LFB		 = 0x8563,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3_SCENE_KEY_3_LFB		 = 0x8564,
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_SCENE_KEY_4_LFB		 = 0x8565,
	REX_OTA_IMAGETYPE_DIMMER_SWITCH_LFB			 	 = 0x8566,
	REX_OTA_IMAGETYPE_EMERGENCY_ALARM_LFB			 = 0x8567,
	REX_OTA_IMAGETYPE_THERMOSTAT_LFB				 = 0x8568,
	REX_OTA_IMAGETYPE_SMART_PLUG_LFB				 = 0x8569,

	/*The following image types are customized for Homy's Telink project to distinguish between 
	the firmware versions for the chip-on-board version and the module version, 
	where "_A" denotes the chip-on-board version and "_B" indicates the module version.*/
	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_1_HOMY_A = 0x856A,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_HOMY_A = 0x856B,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3_HOMY_A = 0x856C,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4_HOMY_A = 0x856D,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_1_HOMY_B = 0x856E,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_HOMY_B = 0x856F,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3_HOMY_B = 0x8570,
    REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4_HOMY_B = 0x8571,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_1_HOMY_A = 0x8572,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_2_HOMY_A = 0x8573,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_3_HOMY_A = 0x8574,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_4_HOMY_A = 0x8575,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_6_HOMY_A = 0x8576,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_1_HOMY_B = 0x8577,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_2_HOMY_B = 0x8578,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_3_HOMY_B = 0x8579,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_4_HOMY_B = 0x857A,
    REX_OTA_IMAGETYPE_SCENE_SELECTOR_KEY_6_HOMY_B = 0x857B,
    REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_1_HOMY_A = 0x857C,
    REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_2_HOMY_A = 0x857D,
    REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_1_HOMY_B = 0x857E,
    REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_2_HOMY_B = 0x857F,
	REX_OTA_IMAGETYPE_ONOFF_SCENE_PANEL_1_HOMY_A = 0x8580,
	REX_OTA_IMAGETYPE_ONOFF_SCENE_PANEL_2_HOMY_A = 0x8581,
	REX_OTA_IMAGETYPE_ONOFF_SCENE_PANEL_3_HOMY_A = 0x8582,
	REX_OTA_IMAGETYPE_ONOFF_SCENE_PANEL_4_HOMY_A = 0x8583,
	REX_OTA_IMAGETYPE_ONOFF_SCENE_PANEL_6_HOMY_A = 0x8584,

	//if have any special device use 0x8800 ~ 0x8E00, note new image type should add by marketing department.
	REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_1		 = 0x8811,
	//1-9 0X8811 - 0X8819
	REX_OTA_IMAGETYPE_WINDOW_COVERING_PANEL_9		 = 0x8819,
	
	REX_OTA_IMAGETYPE_SINGLE_FIRE_VARIABLE_KEY		 = 0x88A0,
	REX_OTA_IMAGETYPE_SINGLE_FIRE_KEY_1		 	     = 0x88A1,
	//1-9	0x88A1 ~ 0x88A9
	REX_OTA_IMAGETYPE_SINGLE_FIRE_KEY_9		 	     = 0x88A9,
	
 	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_SCENE_KEY_2     = 0x88AA, 
  	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_3_SCENE_KEY_3     = 0x88AB, 
  	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_4_SCENE_KEY_2     = 0x88AC, 
  	REX_OTA_IMAGETYPE_ON_OFF_LIGHT_KEY_2_SCENE_KEY_4     = 0x88AD, 

	REX_OTA_IMAGETYPE_DO_NOT_CONFIRM		 		 = 0xffff,
} rex_ota_image_type_enum_t;

//  0x8500 ~ 0x8FFF reserved used for combine device 


#endif
